package PaooGame.Character;

import javax.swing.*;
import java.awt.*;

public class CharacterMenuWindow {
    private JButton attackButton;
    private JPanel panel1;

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        attackButton = new JButton();
        attackButton.setText("Attack");
        panel1.add(attackButton, BorderLayout.NORTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public CharacterMenuWindow() {
        $$$setupUI$$$();
        panel1.setBackground(Color.red);
        panel1.setSize(114, 240);
        panel1.setVisible(false);
        panel1.setLayout(null);
    }

    public JPanel getPanel1() {
        return panel1;
    }
}
